# Generated by Django 3.2.7 on 2021-09-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='User_ID2',
        ),
        migrations.AddField(
            model_name='comment',
            name='Incognito',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='ContributeID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='staff.contribution'),
        ),
    ]
