# Generated by Django 3.2.7 on 2021-09-23 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210919_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('ContributeID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='staff.contribution')),
            ],
        ),
    ]
