# Generated by Django 3.2.7 on 2021-09-23 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='ContributeID',
        ),
        migrations.AddField(
            model_name='contribution',
            name='TypeID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.type'),
        ),
    ]
